spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${REMEMBER_MAIN_DB_HOST}:${REMEMBER_MAIN_DB_PORT}/${REMEMBER_MAIN_DB_NAME}?characterEncoding=UTF-8&serverTimezone=UTC
    username: ${REMEMBER_MAIN_DB_USER}
    password: ${REMEMBER_MAIN_DB_PASSWORD}
