spring:
  data:
    rest:
      detection-strategy: annotated
      default-page-size: 20
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: url
    username: username
    password: password
